### ISSUE TITLE
project: no license / not licensed

### ISSUE THREAD

**Issue by kardianos** [cheynewallace/tabby#2]
Hello,

I was just about to use your project, when I saw that it isn't licensed anywhere in writing. I the country I reside, that means I don't have a license and can't use it.

If this was intended to be an open source / freely available, I would recommend putting a license within the project.

Thanks, -Daniel

**Comment by cheynewallace** [comment]
Good point, thanks for pointing that out @kardianos  👍

**Comment by cheynewallace** [comment]
Thats done @kardianos 
https://github.com/cheynewallace/tabby/blob/master/LICENSE
